
#ifndef ___HEADFILE_B3D1D8B6_CD77_4FB3_A62E_A83D30BA0451_
#define ___HEADFILE_B3D1D8B6_CD77_4FB3_A62E_A83D30BA0451_

#include "../big_integer.h"


namespace nut
{

/**
 * A simple bit sieve used for finding prime number candidates. Allows setting
 * and clearing of bits in a storage array. The size of the sieve is assumed to
 * be constant to reduce overhead. All the bits of a new BitSieve are zero, and
 * bits are removed from it by setting them.
 *
 * To reduce storage space and increase efficiency, no even numbers are
 * represented in the sieve (each bit in the sieve represents an odd number).
 * The relationship between the index of a bit and the number it represents is
 * given by
 * N = offset + (2*index + 1);
 * Where N is the integer represented by a bit in the sieve, offset is some
 * even integer offset indicating where the sieve begins, and index is the
 * index of a bit in the sieve array.
 *
 * @see     BigInteger
 * @version 1.13, 11/07/08
 * @author  Michael McCloskey
 * @since   1.3
 */
class BitSieve
{
public:
    /**
     * Construct a bit sieve of search_len bits used for finding prime number
     * candidates. The new sieve begins at the specified base, which must
     * be even.
     */
    BitSieve(const BigInteger& base, int search_len) noexcept;

    ~BitSieve() noexcept;

    /**
     * Test probable primes in the sieve and return successful candidates.
     */
    BigInteger retrieve(const BigInteger& init_value, int certainty) noexcept;

private:
    BitSieve(const BitSieve&) = delete;
    BitSieve& operator=(const BitSieve&) = delete;

    /**
     * Construct a "small sieve" with a base of 0.  This constructor is
     * used internally to generate the set of "small primes" whose multiples
     * are excluded from sieves generated by the main (package private)
     * constructor, BitSieve(BigInteger base, int search_len).  The length
     * of the sieve generated by this constructor was chosen for performance;
     * it controls a tradeoff between how much time is spent constructing
     * other sieves, and how much time is wasted testing composite candidates
     * for primality.  The length was chosen experimentally to yield good
     * performance.
     */
    BitSieve() noexcept;

    /**
     * Get the value of the bit at the specified index.
     */
    bool get(int bit_index) noexcept;

    /**
     * Set the bit at the specified index.
     */
    void set(int bit_index) noexcept;

    /**
     * This method returns the index of the first clear bit in the search
     * array that occurs at or after start. It will not search past the
     * specified limit. It returns -1 if there is no such clear bit.
     */
    int sieve_search(int limit, int start) noexcept;

    /**
     * Sieve a single set of multiples out of the sieve. Begin to remove
     * multiples of the specified step starting at the specified start index,
     * up to the specified limit.
     */
    void sieve_single(int limit, int start, int step) noexcept;

private:
    /**
     * Stores the bits in this BitSieve.
     */
    int64_t *_bits = nullptr;
    int _bits_cap = 0;

    /**
     * Length is how many bits this sieve holds.
     */
    int _length = 0;

    /**
     * A small sieve used to filter out multiples of small primes in a search
     * sieve.
     */
    static BitSieve _small_sieve;
};

}

#endif
