#!/usr/bin/env groovy

pipeline {
    agent none

    stages {
        stage ('Build and test') {
            agent {
                label 'linux'
            }
            steps {
                sh 'cd proj/makefile; make DEBUG=1 -j$(nproc --all) run'
            }
        }
    }
}
